country:
    name: india

user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

baseURL:
    country-info: https://disease.sh/v3/covid-19/gov/